name: tick_market
description: A real-time simulated Bitcoin market with adaptive chart delivery.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  fl_chart: 1.2.0
  flutter_bloc: 9.1.1
  bloc_concurrency: 0.3.0
  equatable: 2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
